Repository SOTAEJI/SamsungAutomationStudio, pull requests merged in 2021-10, with the labels that each got.

#5 merge: feature/drive to develop
  501-FileCloud.html
  501-FileCloud.js
  icons/googleDrive.png
  icons/onedrive.png
  lib/googleApi.js
  lib/oneApi.js
  package.json
Labels: enhancement

#7 release: 1.0.0
  401-DataFormatter.js
Labels: release

#10 fix: fix overallStatistics function and add y_label form
  401-DataFormatter.html
  401-DataFormatter.js
Labels: bug
